compute_environment: LOCAL_MACHINE
deepspeed_config: 
  deepspeed_config_file: configs/deepspeed/ds_config_zero2.json
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false