train:
  seq_length: 2048
  epochs: 10000
  total_steps: 100000
  batch_size: 4  # train_micro_batch_size_per_gpu

  checkpoint_interval: 1000
  eval_interval: 200

  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"
  tracker: "tensorboard"

model:
  model_path: "CarperAI/openai_summarize_tldr_sft"
  num_layers_unfrozen: 8

tokenizer:
  tokenizer_path: "CarperAI/openai_summarize_tldr_sft"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6 # was 4e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 1000000  # train.total_steps
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 256
  chunk_size: 32
  ppo_epochs: 4
  init_kl_coef: 0.1
  target: 6  # 0.01
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: null
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 50
